name: Build

on:
  push

env:
  SOLUTION_FILE_PATH: Xaudio2Hrtf.sln
  BUILD_CONFIGURATION: Release

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: .Net Build
      uses: EasyDesk/action-dotnet-build@v1.0.0
      with:
        build-configuration: ${{env.BUILD_CONFIGURATION}}
        path: Xaudio2Hrtf.sln
