name: Build

on:
  push

env:
  SOLUTION_FILE_PATH: Xaudio2Hrtf.sln
  BUILD_CONFIGURATION: Release

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        vs-version: 14.0
        msbuild-architecture: x64
        
    - name: Build app for release
      run: msbuild Xaudio2Hrtf.sln -t:rebuild -verbosity:diag -property:Configuration=Release
